"""
=========================================================
Jazz Groove Analyzer (JGA)

File:
    runtime_event.py

Description:
    Semantic runtime event emitted by the JGA
    analysis pipeline.

Author:
    Angelo Tracanna

Copyright © 2026 Angelo Tracanna
All Rights Reserved.
=========================================================
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(frozen=True, slots=True)
class RuntimeEvent:
    """
    Immutable semantic event generated by a
    completed architectural transformation.
    """

    event_id: str

    layer: str

    component: str

    message: str

    input_type: str | None = None

    output_type: str | None = None

    metrics: dict[str, Any] = field(
        default_factory=dict
    )

    timestamp: datetime = field(
        default_factory=datetime.now
    )
