from pathlib import Path
import sys,json,csv,hashlib,datetime,collections
import numpy as np,soundfile as sf
W=Path(__file__).resolve().parent;sys.path.insert(0,str(W/'development'));from selector import associate,metrics
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):p.write_text(json.dumps(x,indent=2,allow_nan=False)+'\n')
H=W/'holdout';fr=json.loads((H/'output/PREDICTIONS_FREEZE.json').read_text());assert all(sha(H/p)==h for p,h in fr['files'].items());records=json.loads((H/'output/BLIND_CANDIDATES.json').read_text());preds={p['BP_id']:p for p in json.loads((H/'output/BLIND_PREDICTIONS.json').read_text())};mapping=json.loads((W/'EVALUATION_MAP.json').read_text());sp=json.loads((W/'TAKE_SPLIT.json').read_text());G=W.parent/'JGA_GALLEGATI_CONTINUOUS_FISHMAN_GT_120_20260924/GROUND_TRUTH';assert sha(G/'GALLEGATI_FISHMAN_CONTINUOUS_ONSET_GT_120_V1.json')=='a4047bf252f28fa3289279bdcaa5e90226dcf0af994a51e0dd5df05174484631'
gt=[dict(g,clip_id=next(k for k,v in mapping.items() if v==g['take_id'])) for g in json.loads((G/'GALLEGATI_FISHMAN_CONTINUOUS_ONSET_GT_120_V1.json').read_text())['events'] if g['take_id'] in sp['holdout']];save(W/'GT_REVEAL_RECORD.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'prediction_freeze_sha256':sha(H/'output/PREDICTIONS_FREEZE.json'),'scope':'Separate evaluation process only; first current holdout evaluation after prediction freeze; prior investigator exposure disclosed.'})
dur={m['clip_id']:sf.info(H/'input'/m['audio']).duration for m in json.loads((H/'input/MANIFEST.json').read_text())};ass=associate(records,gt,dur);rows=[];methods=['native_BP','nearest_BP','earliest','largest_flux','JGA'];covered={k:0 for k in [5,10,20]}
for a in ass:
 g=a['GT'];r=a['record'];t=float(g['final_center_s']);lo=float(g['final_earliest_s']);hi=float(g['final_latest_s']);row={'take':g['take_id'],'GT_ID':g['event_id'],'string':g['string'],'condition':g['dynamic'],'pitch':g['midi_pitch'],'clip_id':g['clip_id'],'GT_onset':t,'GT_lower':lo,'GT_upper':hi,'BP_association':a['association'],'BP_id':'','BP_onset':None,'candidate_count':None,'selected_candidate':None,'selector_status':'BP_CORRESPONDENCE_UNRESOLVED','signed_error_ms':None,'absolute_error_ms':None,'interval_relation':'','associated_BP_ids':';'.join(a['associated_BP_ids'])}
 for method in methods:row[method+'_error_ms']=None
 if r:
  bp=r['BP']['onset_local_s'];cand=r['candidates'];p=preds[r['BP']['native_note_id']];row.update(BP_id=r['BP']['native_note_id'],BP_onset=bp,candidate_count=len(cand),selected_candidate=p['selected_s'],selector_status=p['status']);times={'native_BP':bp,'nearest_BP':min(cand,key=lambda c:abs(c['time_s']-bp))['time_s'] if cand else None,'earliest':min(c['time_s'] for c in cand) if cand else None,'largest_flux':max(cand,key=lambda c:c['flux'])['time_s'] if cand else None,'JGA':p['selected_s']}
  for k in covered:covered[k]+=int(any(abs(c['time_s']-t)<=k/1000 for c in cand))
  for method,tm in times.items():row[method+'_error_ms']=(tm-t)*1000 if tm is not None else None
  if p['selected_s'] is not None:row.update(signed_error_ms=row['JGA_error_ms'],absolute_error_ms=abs(row['JGA_error_ms']),interval_relation='BEFORE' if p['selected_s']<lo else 'AFTER' if p['selected_s']>hi else 'INSIDE')
 rows.append(row)
assert len(rows)==40
with (W/'HOLDOUT_ATTACK_SELECTIONS.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
save(W/'HOLDOUT_RESULTS.json',rows)
def summary(rs):
 resolved=[r for r in rs if r['BP_onset'] is not None];selected=[r for r in rs if r['signed_error_ms'] is not None];return {'GT_events':len(rs),'BP_recognized_unique':len(resolved),'BP_correspondence_unresolved':len(rs)-len(resolved),'status_counts':dict(collections.Counter(r['selector_status'] for r in rs)),'selected_correct_association_within100ms':sum(abs(r['signed_error_ms'])<=100 for r in selected),'wrong_selections_beyond100ms':sum(abs(r['signed_error_ms'])>100 for r in selected),'selected_errors_over20ms':sum(abs(r['signed_error_ms'])>20 for r in selected),'missed_or_unresolved':len(rs)-sum(abs(r['signed_error_ms'])<=100 for r in selected),'interval_counts':dict(collections.Counter(r['interval_relation'] for r in selected)),'selection_coverage_all_GT_pct':100*len(selected)/len(rs),'selection_coverage_recognized_pct':100*len(selected)/len(resolved) if resolved else None,'methods':{method:metrics([r[method+'_error_ms'] for r in rs if r[method+'_error_ms'] is not None],len(rs)) for method in methods}}
result={'pooled':summary(rows),'candidate_coverage':covered,'all_raw_BP_queries':len(records),'all_query_status_counts':dict(collections.Counter(p['status'] for p in preds.values())),'by_string':{s:summary([r for r in rows if r['string']==s]) for s in sorted({r['string'] for r in rows})},'by_condition':{s:summary([r for r in rows if r['condition']==s]) for s in sorted({r['condition'] for r in rows})},'by_take':{s:summary([r for r in rows if r['take']==s]) for s in sorted({r['take'] for r in rows})}}
save(W/'EVALUATION.json',result);save(W/'EVALUATION_FREEZE.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':{p:sha(W/p) for p in ['HOLDOUT_ATTACK_SELECTIONS.csv','HOLDOUT_RESULTS.json','EVALUATION.json','evaluate.py']}});print(json.dumps(result['pooled'],indent=2));print('ALL QUERIES',result['all_query_status_counts'])
