"""
=========================================================
Jazz Groove Analyzer (JGA)

File:
    ensemble_metric_event.py

Description:
    Represents one Ensemble Metric Event (EME).

Author:
    Angelo Tracanna

Copyright © 2026 Angelo Tracanna
All Rights Reserved.
=========================================================
"""

from dataclasses import dataclass, field

from jga.core.metric_contribution import MetricContribution


@dataclass(slots=True)
class EnsembleMetricEvent:
    """
    Ensemble Metric Event.

    Generated by the temporal consensus
    of multiple metric sources.
    """

    # Time interval occupied by the event
    start_time: float

    end_time: float

    # Estimated beat position
    beat_time: float

    # Contributions
    contributions: list[MetricContribution] = field(default_factory=list)

    # Overall confidence
    confidence: float = 1.0

    @property
    def duration(self) -> float:
        return self.end_time - self.start_time

    @property
    def source_count(self) -> int:
        return len(self.contributions)