from pathlib import Path
import json,hashlib,shutil,csv,numpy as np,datetime
W=Path(__file__).resolve().parent;R=W.parent;P=R/'JGA_BASS_V1_HISTORICAL_TRANSFER_20260924';S=R/'JGA_LEARNED_LOCAL_ATTACK_SELECTOR_20260924';I=W/'inference';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):p.write_text(json.dumps(x,indent=2)+'\n')
checks={}
for base,fp in [(P/'inference',P/'inference/output/HISTORICAL_ACOUSTIC_FREEZE.json'),(P,P/'ROUTING_FREEZE.json'),(S/'development',S/'development/output/SELECTOR_FREEZE.json')]:
 f=json.loads(fp.read_text());assert all(sha(base/p)==h for p,h in f['files'].items());checks[str(fp)]=sha(fp)
for name in ['BLIND_CANDIDATES.json','QUERY_DECISIONS.json','EPISODE_DECISIONS.json','UNIQUE_ACOUSTIC_ATTACKS.json']:shutil.copyfile(P/'inference/output'/name,I/'input'/name)
shutil.copyfile(P/'inference/morphology.py',I/'morphology.py');shutil.copyfile(P/'inference/input/SELECTOR_RULE.json',I/'input/SELECTOR_RULE.json')
audit=json.loads((P/'INPUT_AUDIT.json').read_text());sources=[]
for s in audit['source_pcm']:
 assert sha(Path(s['source']))==s['sha256'];shutil.copyfile(s['source'],I/'input'/('FULLMIX.wav' if s['signal']=='mix' else 'BASS.wav'));sources.append(s)
# Reference feature distribution only; no controlled GT timestamp is sent to diagnostic process.
cs=list(csv.DictReader((S/'development/output/DEVELOPMENT_CANDIDATES.csv').open()));names=json.loads((I/'input/SELECTOR_RULE.json').read_text())['features'];ref={}
for label in ['INTERVAL_COMPATIBLE','NEAR_INTERVAL_PROXY','NEGATIVE']:
 rows=[r for r in cs if r['label']==label];ref[label]={'N':len(rows),'features':{n:{'p10':float(np.percentile([float(r[n]) for r in rows],10)),'median':float(np.median([float(r[n]) for r in rows])),'p90':float(np.percentile([float(r[n]) for r in rows],90))} for n in names} if rows else {}}
save(I/'input/CONTROLLED_FEATURE_REFERENCE.json',ref)
protocol={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'Diagnostic/descriptive only; no full-mix logistic inference, no replacement attack timestamps, no PLP evaluation planned. Previously PLP-exposed investigator; process isolated.','windows':'Reuse exact per-query search_start/end from frozen historical candidates; contained and unchanged. STFT context identical to frozen generator (150ms outside for feature support only), but full-mix candidates retained strictly inside frozen query window.','representation':'Identical Hann1024/hop44,44100Hz,positive magnitude flux30<=f<250 and native frame centers, stereo arithmetic mean. No stem candidate regeneration. Full-mix peak enumeration reuses frozen morphology code; no learned decision applied.','salience_flag':'Diagnostic display/classification aid only: prominence > median(window prominences)+3*MAD(window prominences), AND existing low_energy_post_pre_logratio>0 AND rms_post_pre_logratio>0. Unscaled MAD. No outcome tuning. All unflagged peaks retained. This is not a validated physical attack detector or a changed frozen selector threshold.','coordinate_relation':'At each stem candidate: count salient full-mix peaks within half Hann support (512/44100 s). Multiple→FULLMIX_MULTIPLE_PLAUSIBLE_FRONTS; single within one hop→FULLMIX_CORRESPONDING_FRONT; single farther→FULLMIX_NEARBY_DISTINCT_FRONT; none→NO_CLEAR_FULLMIX_FRONT. Also preserve nearest raw full-mix peak and its qualification separately. These are resolution-linked descriptive correspondences, not source proof.','episode_aggregation':'Union candidate RECORDS from separate member windows by exact native PCM coordinate only; no search-window bridging. One salient coordinate→clear local-front cue; more than one→multiple; zero→no clear cue. Every independent query window remains separate.','selected17':'For each previous selected episode use salient full-mix coordinates across its exact routed windows. One within one hop of stem→supports stem selection; one earlier/later→different earlier/later; multiple→ambiguous; none→no support. Support means full-mix acoustic cue only, not Bass identification.','late_cohort':'Selected stem minus any successful native BP query onset >one Hann support(1024/44100s), plus PI-namedHF044/HF047 explicitly regardless. No timestamp replacement.','limits':'Other instruments can dominate full-mix low-band transients. Cue absence does not establish no physical attack. Domain comparisons descriptive, model coefficient contributions associative; no causal latency inference.'}
save(W/'PROTOCOL.json',protocol);save(W/'INPUT_AUDIT.json',{'verified_freezes':checks,'source_PCM':sources,'routing_unchanged':True,'no_model_weights_copied_to_inference':True,'controlled_reference':'Previously labelled developmental feature distributions only; no GT coordinates.'})
save(W/'INPUT_FREEZE.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':{str(p.relative_to(W)):sha(p) for p in [W/'PROTOCOL.json',W/'INPUT_AUDIT.json',I/'morphology.py',*sorted((I/'input').glob('*.json'))]}})
s='(version 1)\n(allow default)\n(deny network*)\n(deny file-read* (subpath "/Users") (subpath "/Volumes") (subpath "/private/tmp"))\n'
for p in [str(I),str(Path('.venv').resolve())]:s+=f'(allow file-read* (subpath "{p}"))\n'
(W/'isolation.sb').write_text(s+'(allow file-read-metadata)\n');print('Verified historical acoustic/routing freezes; exact windows and candidates copied; full-mix descriptive protocol saved.')
