from pathlib import Path
import os,json,hashlib,re,datetime
os.environ['MPLCONFIGDIR']='/private/tmp/jga_contained_mpl'
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
W=Path(__file__).resolve().parent;I=W/'inference';rs=json.loads((W/'EVENT_RESULTS.json').read_text());r=json.loads((W/'RESULTS.json').read_text());qs=json.loads((I/'output/INDEPENDENT_WINDOW_DECISIONS.json').read_text());plt.rcParams.update({'font.size':9})
with PdfPages(W/'CONTAINED_FALLBACK_REVIEW.pdf') as pdf:
 fig,axs=plt.subplots(2,1,figsize=(13,8),layout='constrained')
 for ax,c in zip(axs,['natural_ambiguous','masked_holdout']):
  rr=[a for a in rs if a['cohort']==c];ax.axhline(0,color='green',lw=.8)
  for k,a in enumerate(rr):
   if a['selected_s'] is None:ax.scatter(k,8,marker='x',color='orange')
   else:ax.scatter(k,a['signed_error_ms'],marker='D' if a['status']=='SHARED_ATTACK_IDENTITY_UNRESOLVED' else 'o',facecolor='none',edgecolor='blue')
  ax.set_xticks(range(len(rr)),[a['event_id'].replace('GAL09_20260914_','') for a in rr],rotation=90,fontsize=6);ax.set_ylim(-12,12);ax.set_ylabel('Selected − GT (ms)');ax.set_title(c)
 fig.suptitle('Contained fallback — all48 cohort entries\n○ one successful hypothesis · ◇ shared native candidate · × abstention status lane (+8, not an error value)');pdf.savefig(fig);plt.close(fig)
 for a in r['previous_catastrophic_cases']:
  ids=a['BP_ids'].split(';');fig,ax=plt.subplots(figsize=(13,5),layout='constrained');t=a['GT_onset_s']
  for k,b in enumerate(ids):
   q=qs[b];ax.plot([q['window_start_s']-t,q['window_end_s']-t],[k,k],lw=6,color='.7')
   if q['selected_s'] is not None:ax.scatter(q['selected_s']-t,k,color='blue');ax.text(q['selected_s']-t,k+.1,f"{(q['selected_s']-t)*1000:+.2f} ms",fontsize=8)
  ax.axvline(0,color='green',label='Human GT');ax.axvline(a['prior_union_error_ms']/1000,color='red',ls='--',label='Previous union selection');ax.set_yticks(range(len(ids)),ids);ax.set_xlabel('Seconds from GT; gray bars are independent native BP windows, gaps never merged');ax.set_title(a['event_id']+'\nABSTAIN_MULTIPLE_DISTINCT_ATTACKS — no cross-window winner');ax.legend();pdf.savefig(fig)
  if a['cohort']=='natural_ambiguous':fig.savefig(W/'CONTAINMENT_PREVIEW.png',dpi=120)
  plt.close(fig)
s=['# Contained multi-hypothesis BP fallback — frozen JGA selector','','**Result: all3previous catastrophic selections become abstentions. Zero catastrophic outputs in the selected cohorts; substantially reduced coverage. Fallback remains CONDITIONAL.**','','## What changed and what did not','','The model, scaler, feature definitions, candidate generator, native candidate coordinates, threshold0.5 and per-window abstention logic are unchanged and hash verified. Each native BP hypothesis retains its original ±150ms window and its own candidate-context features. The exact frozen decide() runs independently for each of760preserved BP queries. No candidate set or search interval is merged across hypotheses.','','For a like-for-like masking comparison, the exact prior BP-only hypothesis-set membership is retained solely as bookkeeping for the requested consensus/abstention test. Old activity envelopes are not used as search windows. This avoids silently restoring the GT-matched BP identity or narrowing the masked population. Same13natural ambiguous and35masked holdout GT IDs.','','Consensus: one successful query yields a selection; multiple successful queries at the exact same original PCM sample yield SHARED_ATTACK_IDENTITY_UNRESOLVED; different sample coordinates yield ABSTAIN_MULTIPLE_DISTINCT_ATTACKS; no successful query abstains. Shared means identical observed spectral coordinate, not independent proof of one physical pluck. No millisecond clustering radius, timestamp averaging or proximity-based collapse was added. The selected timestamp remains an original candidate coordinate.','','The prior investigator exposure remains a limitation. Inference was filesystem-isolated from GT, prior evaluation results and cohort IDs;3negative-read probes passed. All per-window outputs and consensus predictions were saved/hashed before GT evaluation. GT target remains Fishman channel-specific observable onset, NOT physical string release.','','## Results','','| Metric | Natural ambiguous | Masked holdout |','|---|---:|---:|']
a=r['natural_ambiguous']['metrics'];b=r['masked_holdout']['metrics']
for title,key in [('Cohort events','total'),('Selected','N'),('Coverage %','coverage_pct'),('Median signed ms','median_signed_ms'),('Mean signed ms','mean_signed_ms'),('Median absolute ms','median_absolute_ms'),('P95 absolute ms','P95_absolute_ms'),('Maximum absolute ms','maximum_absolute_ms'),('Within ±5ms, selected %','within_5_pct'),('Within ±10ms, selected %','within_10_pct'),('Within ±20ms, selected %','within_20_pct'),('Within ±30ms, selected %','within_30_pct'),('Useful within10ms yield / all events %','useful_yield_10_pct')]:s.append(f'| {title} | {a[key]:.3f} | {b[key]:.3f} |')
s+=['','Natural13:6single-hypothesis selections,2shared-coordinate selections,5distinct-attack abstentions. Masked35:14single-hypothesis selections,4shared-coordinate selections,17distinct-attack abstentions. No zero-candidate/zero-selected abstentions in these cohorts. Combined shared cases6. Catastrophic wrong-event outputs (>100ms, prior scoring criterion):0in both cohorts. No selected error exceeds10ms.','','## Previous3 catastrophic cases','','| Event | Previous error ms | Contained outcome |','|---|---:|---|']
for a in r['previous_catastrophic_cases']:s.append(f"| {a['event_id']} | {a['prior_union_error_ms']:+.3f} | {a['previous_catastrophic_outcome']} ({a['distinct_selected_coordinates']} distinct coordinates) |")
s+=['','All three are ABSTAIN, not recovered correct attacks. The rule removes the union’s cross-window maximum-score winner: distant competing fronts now trigger explicit ambiguity. It does not solve temporal ownership among competing windows.','','## Interpretation','','TEMPORAL CONTAINMENT SOLVES UNION-WINDOW FAILURE: PARTIAL. It eliminates the observed catastrophic emissions through abstention, while selected-event timing stays around5ms. However natural useful yield drops from12/13to8/13, masked useful yield from33/35to18/35. Zero failures among these small selected cohorts is not proof of a controlled universal wrong-event rate.','','AMBIGUOUS-BP FALLBACK VALIDATED: CONDITIONAL — useful conservative recovery in this bounded corpus, not complete fallback validation. Natural13includes8development-take cases; investigator has prior corpus exposure. The masked test has35previously resolved holdout events. No new independent test corpus or BP-blind capability is established. No rule adjusted after evaluation.','','FROZEN JGA SELECTOR MODIFIED:NO','CONTAINED FALLBACK COVERAGE:61.54% (8/13 natural)','CONTAINED FALLBACK WITHIN ±10ms:100% of8selected','CONTAINED FALLBACK MEDIAN ABSOLUTE ERROR:4.822ms','CONTAINED FALLBACK P95 ABSOLUTE ERROR:5.480ms','CATASTROPHIC WRONG-EVENT SELECTIONS:0','PREVIOUS3CATASTROPHIC CASES:ABSTAIN / ABSTAIN / ABSTAIN','MASKED HOLDOUT COVERAGE:51.43% (18/35)','MASKED HOLDOUT WITHIN ±10ms:100% of18selected','SHARED_ATTACK_IDENTITY_UNRESOLVED CASES:6 (2natural,4masked)','','## Artifacts','','CONTAINED_FALLBACK_RESULTS.csv preserves all48rows; CONTAINED_FALLBACK_REVIEW.pdf shows all cohort outcomes and the3previous failures. inference/output contains760independent-window decisions,137hypothesis-set decisions and prediction hashes. Input and evaluation freezes preserve provenance.','','GT, native BP, prior selector and all previous artifacts unchanged. No historical transfer, canonical change, commit or push. Stop for PI review.']
(W/'RESULT.md').write_text('\n'.join(s)+'\n')
# Validate immutable authorities, memberships, status logic, dates and figures.
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for base,fp in [(W,W/'INPUT_FREEZE.json'),(I,I/'output/PREDICTION_FREEZE.json'),(W,W/'EVALUATION_FREEZE.json')]:
 f=json.loads(fp.read_text());assert all(sha(base/p)==h for p,h in f['files'].items())
records={a['BP']['native_note_id']:a for a in json.loads((I/'input/CANDIDATES.json').read_text())};assert len(qs)==760
for k,q in qs.items():
 if q['selected_s'] is not None:assert q['window_start_s']<=q['selected_s']<=q['window_end_s'];assert q['selected_s'] in [c['time_s'] for c in records[k]['candidates']]
assert len(rs)==48;assert len(r['previous_catastrophic_cases'])==3;assert all(x['previous_catastrophic_outcome']=='ABSTAIN' for x in r['previous_catastrophic_cases']);assert sum(x['catastrophic_wrong_event'] for x in rs)==0
assert all(c['read_denied'] for c in json.loads((I/'output/ISOLATION_CHECKS.json').read_text()))
assert len(re.findall(rb'/Type /Page\b',(W/'CONTAINED_FALLBACK_REVIEW.pdf').read_bytes()))==4
predtime=json.loads((I/'output/PREDICTION_FREEZE.json').read_text())['utc'];reveal=json.loads((W/'GT_REVEAL.json').read_text())['utc'];assert predtime<reveal
(W/'VALIDATION.json').write_text(json.dumps({'status':'PASS','hashes_verified':True,'native_windows_and_coordinates_preserved':True,'independent_queries':760,'cohort_rows':48,'catastrophic_outputs':0,'previous3_all_abstain':True,'GT_reveal_after_prediction_freeze':True,'PDF_pages':4},indent=2)+'\n');print('Report, review PDF and validations complete')
