from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True, slots=True)
class ElementaryMetricEvent:
    """
    Smallest observable temporal entity of the Jazz Groove Analyzer.

    An ElementaryMetricEvent (EME) represents one metric-relevant musical
    event generated by exactly one MetricContributor.

    It is an observation, not an estimation.
    """

    id: UUID
    contributor_id: UUID
    timestamp: float
    confidence: float
    created_at: datetime

    def __post_init__(self) -> None:
        if self.timestamp < 0.0:
            raise ValueError("timestamp must be non-negative")

        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")