from pathlib import Path
import json,hashlib,datetime,csv,collections,sys
W=Path(__file__).resolve().parent;P=W.parent/'JGA_LEARNED_LOCAL_ATTACK_SELECTOR_20260924';I=W/'inference';sys.path.insert(0,str(I));from selector import metrics
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):p.write_text(json.dumps(x,indent=2)+'\n')
f=json.loads((I/'output/RECOVERY_FREEZE.json').read_text());assert all(sha(I/p)==h for p,h in f['files'].items());G=W.parent/'JGA_GALLEGATI_CONTINUOUS_FISHMAN_GT_120_20260924/GROUND_TRUTH';assert sha(G/'GALLEGATI_FISHMAN_CONTINUOUS_ONSET_GT_120_V1.json')=='a4047bf252f28fa3289279bdcaa5e90226dcf0af994a51e0dd5df05174484631'
save(W/'GT_REVEAL.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'prediction_freeze_sha256':sha(I/'output/RECOVERY_FREEZE.json'),'note':'Evaluation after freeze; previous investigator exposure retained.'})
gt=json.loads((G/'GALLEGATI_FISHMAN_CONTINUOUS_ONSET_GT_120_V1.json').read_text())['events'];gmap={g['event_id']:g for g in gt};pops=json.loads((W/'EVALUATION_POPULATIONS.json').read_text());ps=json.loads((I/'output/PREDICTIONS.json').read_text());pmap={p['group_id']:p for p in ps};bmap={k:p['group_id'] for p in ps for k in p['BP_ids']};rows=[]
for cohort,events in pops.items():
 for ev in events:
  g=gmap[ev['event_id']];groups=sorted({bmap[k] for k in ev['BP_ids']});components=[pmap[k] for k in groups];one=len(groups)==1;p=components[0] if one else None;selected=p['selected_s'] if one else None;status=p['selector_status'] if one else 'ABSTAIN_AMBIGUOUS';t=float(g['final_center_s']);error=(selected-t)*1000 if selected is not None else None;interval='BEFORE' if selected is not None and selected<float(g['final_earliest_s']) else 'AFTER' if selected is not None and selected>float(g['final_latest_s']) else 'INSIDE' if selected is not None else ''
  rows.append({'event_id':ev['event_id'],'take':g['take_id'],'string':g['string'],'condition':g['dynamic'],'cohort':cohort,'recovery_mode':'BP_TEMPORAL_ONLY','native_BP_hypotheses':sum(len(c['BP_ids']) for c in components),'recovery_group_ids':';'.join(groups),'region_start':min(lo for c in components for lo,hi in c['search_intervals']),'region_end':max(hi for c in components for lo,hi in c['search_intervals']),'search_intervals_json':json.dumps([a for c in components for a in c['search_intervals']]),'candidate_context_count':sum(c['candidate_context_count'] for c in components),'selector_status':status,'selected_timestamp':selected,'GT_onset':t,'GT_lower':float(g['final_earliest_s']),'GT_upper':float(g['final_latest_s']),'signed_error_ms':error,'absolute_error_ms':abs(error) if error is not None else None,'catastrophic_wrong_event':abs(error)>100 if error is not None else False,'interval_relation':interval,'notes':'One frozen operational BP activity component; exact original selector output' if one else 'Competing correspondence IDs span multiple pre-frozen operational components; no GT choice allowed; abstain'})
with (W/'JGA_BP_AMBIGUITY_RECOVERY.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
save(W/'EVENT_RESULTS.json',rows)
oldrows=json.loads((P/'HOLDOUT_RESULTS.json').read_text());secure={r['GT_ID']:r for r in oldrows if r['BP_id']};result={}
for cohort in pops:
 rs=[r for r in rows if r['cohort']==cohort];errs=[r['signed_error_ms'] for r in rs if r['signed_error_ms'] is not None];m=metrics(errs,len(rs));result[cohort]={'events':len(rs),'counts':dict(collections.Counter(r['selector_status'] for r in rs)),'metrics':m,'catastrophic_over100ms':sum(r['catastrophic_wrong_event'] for r in rs),'errors_over20ms':sum(abs(e)>20 for e in errs),'errors_over30ms':sum(abs(e)>30 for e in errs),'interval_counts':dict(collections.Counter(r['interval_relation'] for r in rs if r['selected_timestamp'] is not None))}
result['secure_same_holdout']=metrics([secure[e['event_id']]['signed_error_ms'] for e in pops['masked_holdout']],35)
result['BP_blind']={'executable':False,'reason':'No pre-existing compatible BP-independent region rule; frozen BP-relative feature inputs undefined.'}
# Prior60 records: verify original prediction freeze and distinguish query membership from temporal evidence.
h=P/'holdout';f=json.loads((h/'output/PREDICTIONS_FREEZE.json').read_text());assert all(sha(h/p)==v for p,v in f['files'].items());priorpred=json.loads((h/'output/BLIND_PREDICTIONS.json').read_text());secureids={r['BP_id'] for r in oldrows if r['BP_id']};extra=[p for p in priorpred if p['status']=='ATTACK_SELECTED' and p['BP_id'] not in secureids];assert len(extra)==60;mapping=json.loads((P/'EVALUATION_MAP.json').read_text());raw=[]
for p in extra:
 take=mapping[p['clip_id']];t=p['selected_s'];matches=[g for g in gt if g['take_id']==take and abs(t-float(g['final_center_s']))<=.1];direct={cohort:[ev['event_id'] for ev in events if p['BP_id'] in ev['BP_ids']] for cohort,events in pops.items()};component_members={cohort:[ev['event_id'] for ev in events if bmap[p['BP_id']] in {bmap[k] for k in ev['BP_ids']}] for cohort,events in pops.items()};raw.append({'BP_id':p['BP_id'],'take':take,'selected_timestamp':t,'operational_group':bmap[p['BP_id']],'cohort_direct_membership':direct,'cohort_component_membership':component_members,'GT_temporally_compatible_ids':[g['event_id'] for g in matches],'GT_errors_ms':[(t-float(g['final_center_s']))*1000 for g in matches],'audit_state':'REFERENCE_TEMPORALLY_COMPATIBLE' if len(matches)==1 else 'MULTIPLE_REFERENCE_COMPATIBILITY' if matches else 'UNVERIFIED_RAW_SELECTION','qualification':'Temporal compatibility is supporting evidence only, not proof of independent physical attack. Raw query multiplicity retained.'})
save(W/'RAW_60_SELECTION_AUDIT.json',raw)
with (W/'RAW_60_SELECTION_AUDIT.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(raw[0]));w.writeheader();w.writerows([{k:json.dumps(v) if isinstance(v,(list,dict)) else v for k,v in r.items()} for r in raw])
result['raw60_audit']={'N':60,'counts':dict(collections.Counter(r['audit_state'] for r in raw)),'unique_selected_coordinates':len({(r['take'],r['selected_timestamp']) for r in raw}),'distinct_GT_compatible':len({g for r in raw for g in r['GT_temporally_compatible_ids']}),'direct_natural_cohort':sum(bool(r['cohort_direct_membership']['natural_ambiguous']) for r in raw),'group_membership_natural':sum(bool(r['cohort_component_membership']['natural_ambiguous']) for r in raw),'group_membership_masked':sum(bool(r['cohort_component_membership']['masked_holdout']) for r in raw)}
result['operational_population']={'native_BP_hypotheses':760,'groups':len(ps),'status_counts':dict(collections.Counter(p['selector_status'] for p in ps))};save(W/'RESULTS.json',result);save(W/'EVALUATION_FREEZE.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':{p:sha(W/p) for p in ['JGA_BP_AMBIGUITY_RECOVERY.csv','EVENT_RESULTS.json','RESULTS.json','RAW_60_SELECTION_AUDIT.json','RAW_60_SELECTION_AUDIT.csv','evaluate.py']}});print(json.dumps(result,indent=2))
